-- MySQL Script generated by MySQL Workbench
-- Thu Jan 19 04:52:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.` curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` curso` (
  `nome` VARCHAR(255) NULL,
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` professor` (
  `id_prof` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `disciplina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_prof`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `quant_aulas` INT NOT NULL,
  ` professor_id_prof` INT NOT NULL,
  PRIMARY KEY (`id_materia`),
  INDEX `fk_materia_ professor1_idx` (` professor_id_prof` ASC) VISIBLE,
  CONSTRAINT `fk_materia_ professor1`
    FOREIGN KEY (` professor_id_prof`)
    REFERENCES `mydb`.` professor` (`id_prof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `data_fim` DATETIME NOT NULL,
  `data_ini` DATETIME NOT NULL,
  `materia_id_materia` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_turma_materia1_idx` (`materia_id_materia` ASC) VISIBLE,
  CONSTRAINT `fk_turma_materia1`
    FOREIGN KEY (`materia_id_materia`)
    REFERENCES `mydb`.`materia` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  ` nome` VARCHAR(45) NOT NULL,
  `data_nasc` DATETIME NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  INDEX `fk_aluno_turma1_idx` (`turma_id_turma` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `mydb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno_matricula` (
  ` curso_id_curso` INT NOT NULL,
  `aluno_id_aluno` INT NOT NULL,
  `id_matricula` INT NOT NULL,
  PRIMARY KEY (` curso_id_curso`, `aluno_id_aluno`, `id_matricula`),
  INDEX `fk_ curso_has_aluno_aluno1_idx` (`aluno_id_aluno` ASC) VISIBLE,
  INDEX `fk_ curso_has_aluno_ curso1_idx` (` curso_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_ curso_has_aluno_ curso1`
    FOREIGN KEY (` curso_id_curso`)
    REFERENCES `mydb`.` curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ curso_has_aluno_aluno1`
    FOREIGN KEY (`aluno_id_aluno`)
    REFERENCES `mydb`.`aluno` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` curso_has_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` curso_has_turma` (
  ` curso_id_curso` INT NOT NULL,
  `turma_id_turma` INT NOT NULL,
  PRIMARY KEY (` curso_id_curso`, `turma_id_turma`),
  INDEX `fk_ curso_has_turma_turma1_idx` (`turma_id_turma` ASC) VISIBLE,
  INDEX `fk_ curso_has_turma_ curso1_idx` (` curso_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_ curso_has_turma_ curso1`
    FOREIGN KEY (` curso_id_curso`)
    REFERENCES `mydb`.` curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ curso_has_turma_turma1`
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `mydb`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
